AZURE_LOCATION: 'australiasoutheast'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'chapooki'
ACCOUNT_NAME: 'chapooki'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'